    post:
      tags:
      - Admins  
      summary: GetDomainSpidrConfigurationRequest
      parameters:
        - name: GetDomainSpidrConfigurationRequest
          in: query
          required: true
          description: GetDomainSpidrConfigurationRequest
          type : string
      responses:
        200:
          description: The request completed successfully
          schema: 
            $ref: '#/definitions/success'  

    