    get:
      tags:
      - Admins  
      summary: GetDomainConfigurationRequest
      responses:
        200:
          description: The request completed successfully
          schema: 
            $ref: '#/definitions/success'  