    post:
      tags:
      - Admins  
      summary: GetDomainSpidrConfigurationRequest
      responses:
        200:
          description: The request completed successfully
          schema: 
            $ref: '#/definitions/success'  

    