    post:
      tags:
      - Admins  
      summary: SetDomainConfigurationRouteRequest
      responses:
        200:
          description: The request completed successfully
          schema: 
            $ref: '#/definitions/success'  
    get:
      tags:
      - Admins  
      summary: GetDomainConfigurationRouteRequest
      responses:
        200:
          description: The request completed successfully
          schema: 
            $ref: '#/definitions/success'  