    get:
      tags:
      - Admins  
      summary: GetApplicationConfigurationRequest
      parameters:
        - name: domain_special_key
          in: query
          required: true
          description: Domain Special Key
          type: string
      responses:
        200:
          description: The request completed successfully
          schema: 
            $ref: '#/definitions/success'  