    get:
      tags:
      - Admins  
      summary: GetDomainConfigurationRequest
      parameters:
        - name: GetDomainConfigurationRequest
          in: query
          required: true
          description: GetDomainConfigurationRequest
          type : string
      responses:
        200:
          description: The request completed successfully
          schema: 
            $ref: '#/definitions/success'  