    post:
      tags:
      - Admins  
      summary: SetAccountConfigurationRequest
      parameters:
        - name: Account Email
          in: query
          required: true
          description: Email
          type: string           
        - name: account_configuration
          in: query
          required: true
          description: Account Configuration
          type : string
      responses:
        200:
          description: The request completed successfully
          schema: 
            $ref: '#/definitions/success'
    get:
      tags:
      - Admins  
      summary: GetAccountConfigurationRequest
      parameters:
        - name: Account Email
          in: query
          required: true
          description: Email
          type: string
      responses:
        200:
          description: The request completed successfully
          schema: 
            $ref: '#/definitions/success'